Repository qbits-mx/tienda-backend, pull requests merged in 2022-01, with the labels that each got.

#142 Feature/crear validar rechazar
  src/main/java/mx/qbits/tienda/api/mapper/GestorAdministradorMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/InformacionAnuncioMapper.java
  src/main/java/mx/qbits/tienda/api/model/domain/InformacionAnuncio.java
  src/main/java/mx/qbits/tienda/api/model/domain/InformacionMultimedia.java
  src/main/java/mx/qbits/tienda/api/rest/GestorAdministradorController.java
  src/main/java/mx/qbits/tienda/api/rest/InformacionAnuncioController.java
  src/main/java/mx/qbits/tienda/api/service/GestorAdministradorService.java
  src/main/java/mx/qbits/tienda/api/service/GestorAdministradorServiceImpl.java
  src/main/java/mx/qbits/tienda/api/service/InformacionAnuncioService.java
  src/main/java/mx/qbits/tienda/api/service/InformacionAnuncioServiceImpl.java
Labels: Helado Oscuro

#151 Feature/comprar producto
  src/main/java/mx/qbits/tienda/api/mapper/CompraMapper.java
  src/main/java/mx/qbits/tienda/api/model/domain/Compra.java
  src/main/java/mx/qbits/tienda/api/model/domain/CompraMultimedia.java
  src/main/java/mx/qbits/tienda/api/model/request/AnuncioRequest.java
  src/main/java/mx/qbits/tienda/api/model/response/CompraResponse.java
  src/main/java/mx/qbits/tienda/api/rest/CompraController.java
  src/main/java/mx/qbits/tienda/api/service/CompraService.java
  src/main/java/mx/qbits/tienda/api/service/CompraServiceImpl.java
  src/test/java/mx/qbits/tienda/api/model/CompraServiceTest.java
Labels: feature, Pum4Developer$

#146 Feature/crear calificacion auditar
  pom.xml
  src/main/java/mx/qbits/tienda/api/config/SwaggerConfig.java
  src/main/java/mx/qbits/tienda/api/mapper/AnuncioMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/ConsultaMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/GenteMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/InfoCompraMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/MultimediaMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/RolMapper.java
  src/main/java/mx/qbits/tienda/api/mapper/UsuarioDetalleMapper.java
  src/main/java/mx/qbits/tienda/api/model/domain/Anuncio.java
  src/main/java/mx/qbits/tienda/api/model/domain/Gente.java
  src/main/java/mx/qbits/tienda/api/model/domain/InfoCompra.java
  src/main/java/mx/qbits/tienda/api/model/domain/InfoVenta.java
  src/main/java/mx/qbits/tienda/api/model/domain/Multimedia.java
  src/main/java/mx/qbits/tienda/api/model/exceptions/BusinessException.java
  src/main/java/mx/qbits/tienda/api/model/exceptions/ChatException.java
  src/main/java/mx/qbits/tienda/api/model/exceptions/CustomException.java
  src/main/java/mx/qbits/tienda/api/model/exceptions/StrengthPasswordValidatorException.java
  src/main/java/mx/qbits/tienda/api/model/exceptions/TransactionException.java
  src/main/java/mx/qbits/tienda/api/model/request/GenteRequest.java
  src/main/java/mx/qbits/tienda/api/rest/AdminController.java
  src/main/java/mx/qbits/tienda/api/rest/AnuncioController.java
  src/main/java/mx/qbits/tienda/api/rest/ConsultaController.java
  src/main/java/mx/qbits/tienda/api/rest/GenteController.java
  src/main/java/mx/qbits/tienda/api/rest/InfoCompraController.java
  src/main/java/mx/qbits/tienda/api/rest/MultimediaController.java
  src/main/java/mx/qbits/tienda/api/rest/RouterController.java
  src/main/java/mx/qbits/tienda/api/service/AccessHelperServiceImpl.java
  src/main/java/mx/qbits/tienda/api/service/AnuncioService.java
  src/main/java/mx/qbits/tienda/api/service/AnuncioServiceImpl.java
  src/main/java/mx/qbits/tienda/api/service/ConsultaService.java
  src/main/java/mx/qbits/tienda/api/service/ConsultaServiceImpl.java
  src/main/java/mx/qbits/tienda/api/service/GenteService.java
  src/main/java/mx/qbits/tienda/api/service/InfoCompraService.java
  src/main/java/mx/qbits/tienda/api/service/InfoCompraServiceImpl.java
  src/main/java/mx/qbits/tienda/api/service/MultimediaService.java
  src/main/java/mx/qbits/tienda/api/service/MultimediaServiceImpl.java
  src/main/java/mx/qbits/tienda/api/support/UploadServiceImpl.java
  src/main/java/mx/qbits/tienda/api/utils/DigestEncoder.java
  src/main/java/mx/qbits/tienda/api/utils/JWTUtil.java
  src/main/java/mx/qbits/tienda/api/utils/ValidadorClave.java
  src/test/java/mx/qbits/tienda/api/model/AnuncioServiceImplTest.java
Labels: Pear Co, feature
